### ISSUE TITLE
Verify safe/unsafe

### ISSUE THREAD

**Issue by sdemarch** [pesimachete/pyNeVer#3]
Right now the verify method in verification.py uses the negation of the property in order to check whether there exists a non-empty intersection between the output reachable set and the unsafe zone. 
In order to define safety properties we need to have two verification methods:

-a) the current one to rename 'verify_unsafety'
-b) a new one to name 'verify_safety' that returns "True" if the property is verified, i.e., the output reachable set is not in the unsafe zone

**Comment by pesimachete** [comment]
I do not think there should be the change of sign of the numbers(when doing the negative of the Y constraints in the case '-s'), but i implemented it anyway(as we agreed)
